{% set name = "libjpeg-turbo" %}
{% set version = "2.0.6" %}
{% set sha256 = "005aee2fcdca252cee42271f7f90574dda64ca6505d9f8b86ae61abc2b426371" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libjpeg-turbo', max_pin='x') }}

requirements:
  build:
    - cmake
    - jom  # [win]
    - make
    - msinttypes  # [win and py<35]
    - yasm
    - {{ compiler('c') }}

test:
  files:
    - testorig.jpg
  commands:
    - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg

about:
  home: https://libjpeg-turbo.org
  license: IJG, modified 3-clause BSD and zlib
  license_file: LICENSE.md
  summary: IJG JPEG compliant runtime library with SIMD and other optimizations
  doc_url: https://libjpeg-turbo.org
  dev_url: https://github.com/libjpeg-turbo/libjpeg-turbo
